const questions = [
  { category: 'Architecture', question: 'How long did it take to build the Empire State Building?', hint: 'From the start of construction to opening day.', seconds: 410 * 86400, actual: '1 year, 45 days', fact: 'Construction rose at an average rate of more than four and a half floors each week.' },
  { category: 'Space', question: 'How long did Apollo 11 take to reach the Moon?', hint: 'From launch to lunar orbit.', seconds: 3 * 86400 + 3 * 3600 + 49 * 60, actual: '3 days, 3 hours, 49 minutes', fact: 'Apollo 11 travelled roughly 384,400 kilometres before entering lunar orbit.' },
  { category: 'Sport', question: 'How long did the longest tennis match in history last?', hint: 'Played at Wimbledon in 2010.', seconds: 11 * 3600 + 5 * 60, actual: '11 hours, 5 minutes', fact: 'The match lasted three days and its final set alone took over eight hours.' },
  { category: 'History', question: 'How long did the Anglo-Zanzibar War last?', hint: 'Often called the shortest war in recorded history.', seconds: 38 * 60, actual: '38 minutes', fact: 'It began after an ultimatum expired and ended with the bombardment of the Sultan’s palace.' },
  { category: 'Nature', question: 'How long does a typical human blink last?', hint: 'From eyelid closing to reopening.', seconds: .12, actual: 'about 120 milliseconds', fact: 'You blink roughly 15–20 times per minute without thinking about it.' },
  { category: 'Space', question: 'How long does sunlight take to reach Earth?', hint: 'From the Sun’s surface to our planet.', seconds: 8 * 60 + 20, actual: '8 minutes, 20 seconds', fact: 'That means we always see the Sun as it was more than eight minutes ago.' },
  { category: 'Engineering', question: 'How long did it take to build the Panama Canal?', hint: 'The main U.S. construction period.', seconds: 10 * 365.25 * 86400, actual: 'about 10 years', fact: 'More than 25,000 workers died during the French and U.S. construction eras.' },
  { category: 'Film', question: 'How long did it take Pixar to make Toy Story?', hint: 'From active production through completion.', seconds: 4 * 365.25 * 86400, actual: 'about 4 years', fact: 'It was the first feature-length film made entirely with computer animation.' },
  { category: 'Ancient world', question: 'How long did it take to build the Great Pyramid of Giza?', hint: 'The commonly cited estimate.', seconds: 20 * 365.25 * 86400, actual: 'about 20 years', fact: 'It remained the world’s tallest human-made structure for nearly 4,000 years.' },
  { category: 'Space', question: 'How long did Voyager 1 take to reach Jupiter?', hint: 'From launch to closest approach.', seconds: 546 * 86400, actual: '546 days', fact: 'Voyager 1 launched in 1977 and is now the most distant human-made object.' }
];

const scales = { large: [{ name: 'years', digits: 4, factor: 365.25 * 86400 }, { name: 'months', digits: 2, factor: 30.4375 * 86400 }, { name: 'days', digits: 3, factor: 86400 }], small: [{ name: 'hours', digits: 2, factor: 3600 }, { name: 'minutes', digits: 2, factor: 60 }, { name: 'seconds', digits: 2, factor: 1 }, { name: 'ms', digits: 3, factor: .001 }] };
let index = 0, score = 0, activeScale = 'large';
let values = { years:0, months:0, days:0, hours:0, minutes:0, seconds:0, ms:0 };
const lock = document.querySelector('#lock');
const $ = s => document.querySelector(s);

function renderLock() {
  lock.innerHTML = '';
  scales[activeScale].forEach(unit => {
    const wrapper = document.createElement('div'); wrapper.className = 'unit';
    const digits = document.createElement('div'); digits.className = 'digits';
    const current = String(values[unit.name]).padStart(unit.digits, '0');
    for (let i = 0; i < unit.digits; i++) { const b = document.createElement('button'); b.className = 'digit'; b.type = 'button'; b.dataset.unit = unit.name; b.dataset.place = unit.digits - i - 1; b.dataset.wheel = '0'; b.textContent = current[i]; b.setAttribute('aria-label', `${unit.name} digit`); b.title = 'Click to increase; right-click to decrease'; b.addEventListener('click', () => changeDigit(b, 1)); b.addEventListener('contextmenu', e => { e.preventDefault(); changeDigit(b, -1); }); b.addEventListener('wheel', e => { e.preventDefault(); b.dataset.wheel = Number(b.dataset.wheel) + e.deltaY; if (Math.abs(Number(b.dataset.wheel)) >= 100) { changeDigit(b, Number(b.dataset.wheel) < 0 ? 1 : -1); b.dataset.wheel = '0'; } }, { passive:false }); digits.append(b); }
    wrapper.append(digits, Object.assign(document.createElement('span'), { className:'unit-name', textContent:unit.name })); lock.append(wrapper);
  });
}
function changeDigit(button, step) { button.textContent = (Number(button.textContent) + step + 10) % 10; syncVisibleValues(); }
function syncVisibleValues() { scales[activeScale].forEach(unit => { values[unit.name] = [...document.querySelectorAll(`[data-unit="${unit.name}"]`)].reduce((n, el) => n * 10 + Number(el.textContent), 0); }); }
function guessSeconds() { syncVisibleValues(); return Object.entries(values).reduce((total, [name, value]) => total + value * [...scales.large, ...scales.small].find(unit => unit.name === name).factor, 0); }
function pretty(seconds) { if (seconds < 1) return `${Math.round(seconds * 1000)} milliseconds`; const units = [[365.25*86400,'year'],[86400,'day'],[3600,'hour'],[60,'minute'],[1,'second']]; const parts=[]; for(const [size,name] of units) { const n=Math.floor(seconds/size); if(n && parts.length < 2) { parts.push(`${n} ${name}${n!==1?'s':''}`); seconds -= n*size; } } return parts.join(', ') || '0 seconds'; }
function loadQuestion() { const q=questions[index]; values = { years:0, months:0, days:0, hours:0, minutes:0, seconds:0, ms:0 }; $('#category').textContent=q.category; $('#question').textContent=q.question; $('#hint').textContent=q.hint; $('#roundLabel').innerHTML=`${String(index+1).padStart(2,'0')} <i></i> ${String(questions.length).padStart(2,'0')}`; $('#pickerSection').classList.remove('hidden'); $('#result').classList.add('hidden'); activeScale='large'; document.querySelectorAll('.scale').forEach(b=>b.classList.toggle('active',b.dataset.scale==='large')); renderLock(); }
function reveal() { const actual=questions[index], guess=guessSeconds(); if (!guess) return; const ratio = Math.max(guess, actual.seconds) / Math.min(guess, actual.seconds); const points=Math.round(1000 * Math.max(0, 1 - Math.log10(ratio)/4)); score += points; $('#score').textContent=`SCORE  ${String(score).padStart(4,'0')}`; let text=ratio<1.15?'Almost perfect.':ratio<1.8?'Excellent instinct.':ratio<3?'Pretty close.':ratio<10?'Wrong scale, good instinct.':'That was a wild guess.'; $('#verdict').textContent=text; $('#guessText').textContent=pretty(guess); $('#actualText').textContent=actual.actual; const direction=guess>actual.seconds?'too long':'too short'; $('#difference').textContent=`You were ${ratio.toFixed(ratio < 10 ? 1 : 0)}× ${direction} · +${points} points`; const scale=Math.max(guess, actual.seconds); $('#actualBar').style.width=`${Math.max(3, actual.seconds / scale * 100)}%`; $('#guessBar').style.width=`${Math.max(3, guess / scale * 100)}%`; $('#fact').textContent=actual.fact; $('#pickerSection').classList.add('hidden'); $('#result').classList.remove('hidden'); }
document.querySelectorAll('.scale').forEach(button => button.addEventListener('click', () => { activeScale=button.dataset.scale; document.querySelectorAll('.scale').forEach(b=>b.classList.toggle('active',b===button)); renderLock(); }));
function startGame() { index=0; score=0; $('#score').textContent='SCORE  0000'; $('#startScreen').classList.add('hidden'); $('#endScreen').classList.add('hidden'); $('#gameHeader').classList.remove('hidden'); $('.card').classList.remove('hidden'); $('#gameFooter').classList.remove('hidden'); loadQuestion(); }
function finishGame() { $('#finalScore').textContent=String(score).padStart(4,'0'); $('#endCopy').textContent=score >= 7000 ? 'Your intuition is remarkably calibrated. Time might not be real, but you seem to have a good handle on it.' : score >= 4000 ? 'A few estimates wandered, but you found the right scale more often than not.' : 'Time is strange. Play again and see whether the second trip through feels any different.'; $('#gameHeader').classList.add('hidden'); $('.card').classList.add('hidden'); $('#gameFooter').classList.add('hidden'); $('#endScreen').classList.remove('hidden'); }
$('#start').addEventListener('click', startGame); $('#playAgain').addEventListener('click', startGame); $('#submit').addEventListener('click', reveal); $('#next').addEventListener('click', () => { if (index === questions.length - 1) finishGame(); else { index += 1; loadQuestion(); } });
